Feature: Sort Sources by Release Date
5etools-mirror-1/5etools-mirror-1.github.io pull request #56
Opened 2022-09-08 01:24 UTC by tzfx

This PR aims to close 5ET-942 -> https://github.com/5etools/tracker/issues/1120

It adds an option in the source filter area to sort the sources by release date. This sort applies to both the full text view in the modal and the mini pills, and persists through refreshes.

https://user-images.githubusercontent.com/51995971/189012596-ded4d95a-6f93-423b-8fae-de2b7571ddbf.mov

2022-09-08 11:33 UTC, TheGiddyLimit requested changes

2022-09-08 11:33 UTC, TheGiddyLimit commented on js/filter.js
> +		opts.itemSortFnMini = opts.itemSortFnMini;
this line is a no-op, was it supposed to do something?

2022-09-08 11:33 UTC, TheGiddyLimit commented on js/filter.js
> -	static _SORT_ITEMS_MINI (a, b) {
the mini pills were specifically ordered to match the 3 sections of the source filter ("standard" sources, "non-standard", sources, "homebrew"), which is broken by the removal of this method. Not sure I like this change (although I'll grant it wasn't great to begin with)

Some visual grouping of the mini pills may need to come first, which should really be its own PR

2022-09-08 11:33 UTC, TheGiddyLimit commented on js/filter.js
> +			new ContextUtil.Action(
Having this split across two buttons feels clumsy, as does not having any display of which method is active. Again likely scope for another PR, but this would be better as e.g. a "two radio buttons" `Action` subtype

2022-09-08 11:33 UTC, TheGiddyLimit commented on js/filter.js
> +		super._doRenderPills();
a bit long-winded, try:

```suggestion
		if (this._meta.sort) this._setSort(sort);
		super._doRenderPills();
```

2022-09-08 11:33 UTC, TheGiddyLimit commented on js/filter.js
> +		const sort = this._meta.sort;
as above

2022-09-08 11:33 UTC, TheGiddyLimit commented on js/filter.js
> +		super._doRenderMiniPills();
This is broken, as it re-arranges the order of the mini pills (which can even be seen in your demo webm) such that source pills get rendered after every other pill, until you refresh, which causes them to jump back to their original place.

2022-09-08 11:33 UTC, TheGiddyLimit commented on js/filter.js
> +	sort: "DEFAULT",
not sure I like this being a "long" string--there's some pretty aggressive URL squishing that gets done when serializing/deserializing these for links, and I'd prefer to keep the character count down where it's "free" to do so. Something like `std` ("standard")/`alp` ("alphabetical")/`dat` ("date") instead perhaps

2022-09-10 01:15 UTC, tzfx commented
@TheGiddyLimit Thanks for the feedback! I'll take a look at making these changes!

2022-09-10 01:26 UTC, tzfx commented on js/filter.js
> -	static _SORT_ITEMS_MINI (a, b) {
I'll revisit this. There was a lot going on in the existing code with the sorts, and I think I removed this one in trying to ensure we could have just one set of sort implementations for both the mini and the standard.

2024-02-21 04:18 UTC, closed without merging