Predefined actions patch
5etools-mirror-1/5etools-mirror-1.github.io pull request #66
Opened 2022-12-19 07:08 UTC by FishCrystals

Adds a predefined actions button to add template actions, currently including most weapons (I think I forgot some) and SRD monster actions. Also appends a hacky "datatype" to makebrew-creature.json that exists just to pull the templates from, no idea if anything else needs to be done for this to be "official". Action to-hits and DCs automatically scale to the creature's stats (using code adapted from utils.js).

Dragon breaths intentionally omitted unless there's a way to add those without bloating the list with forty near-identical actions oof

This entire thing is hacky and this is my first time actually tinkering with the code and offering it to a github repo, I hope it's good enough! If not, I'll still find use for it and it was fun to try!

2022-12-19 10:07 UTC, TheGiddyLimit requested changes
A fine plan

Needs to have `npm test` run, as the JS doesn't look linted (`npm run lint:js` will handle this), and this JSON is either not schema-compliant, or the schema for this file is not sufficiently restrictive--either way, the schema (`test/schema-template/makebrew-creature.json`) will need fixed

The copy-paste from `utils.js` is meh, but I'll refactor that later, so don't worry about it

2022-12-19 13:41 UTC, FishCrystals commented on data/makebrew-creature.json
> +        {
1. That does sound like a good approach to me! I'm admittedly not at all a "good" programmer so I wouldn't know where to begin to actually do this, though.
2. I did think of that, although I left that alone for now also due to aforementioned lack of experience. I mostly cobbled this for my own use but it garnered enough interest for me to expand a bit to my ability :D

As for schemas and such, I suspected that there'd be some form of backend stuff I'd run into trouble with and sadly that's where my familiarity with the program ends. But I'm happy that it got noticed!

2022-12-19 15:36 UTC, revilowaldow commented on js/makebrew-creature.js
> +													return Math.floor(eval(clean));
eslint objects to the use of `eval` here

2022-12-19 16:06 UTC, revilowaldow commented
Patch file that does the necessary linting, testing and updates to the schema etc.
[SchemaAndLint.patch](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/files/10260799/SchemaAndLint.patch)
You can apply the changes by adding the file to the root of the repo and running `git apply SchemaAndLint.patch` then deleting the patch file and committing the changes

2023-01-04 15:19 UTC, TheGiddyLimit commented
Added for next release

2023-01-04 15:19 UTC, closed without merging